name: Deploy gh-pages
description: Deploy to GitHub Pages
inputs:
  # github_token:
  #   description: secrets.GITHUB_TOKEN
  #   required: true
  remote_name:
    description: Name of the remote
    required: false
    default: origin
  main_branch:
    description: Name of the main branch
    required: false
    default: main
  target_branch:
    description: Name of the branch to deploy
    required: false
    default: gh-pages
  build_dir:
    description: Output directory of built files
    required: false
    default: dist
  target_dir:
    description: Directory where built files will be published
    required: false
  branch_build:
    description: Whether to deploy a branch build to a subdirectory
    required: false

runs:
  using: node12
  main: build-and-deploy.js
  # env:
  #   # GITHUB_TOKEN: ${{ inputs.github_token }}
  #   REMOTE_NAME: ${{ inputs.remote_name }}
  #   MAIN_BRANCH: ${{ inputs.main_branch }}
  #   TARGET_BRANCH: ${{ inputs.target_branch }}
  #   BUILD_DIR: ${{ inputs.build_dir }}
  #   TARGET_DIR: ${{ inputs.target_dir }}
  #   BRANCH_BUILD: ${{ inputs.branch_build }}
