name: Deploy gh-pages
description: Deploy to GitHub Pages
inputs:
  remote_name:
    description: Name of the remote
    required: false
    default: origin
  main_branch:
    description: Name of the main branch
    required: false
    default: main
  target_branch:
    description: Name of the branch to deploy
    required: false
    default: gh-pages
  build_dir:
    description: Output directory of built files
    required: false
    default: dist
  target_dir:
    description: Directory where built files will be published
    required: false
  github_token:
    description: secrets.GITHUB_TOKEN
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.remote_name }}
    - ${{ inputs.main_branch }}
    - ${{ inputs.target_branch }}
    - ${{ inputs.build_dir }}
    - ${{ inputs.target_dir }}
    - ${{ inputs.github_token }}
