on:
  push:
    branches:
      - main

jobs:
  deploy_github_pages:
    runs-on: ubuntu-20.04
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: yarn
      - run: yarn test
      - name: Deploy
        id: deploy
        uses: ./
        # with:
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # target_branch: main
          # build_dir: dist
          # target_dir: docs
