on: [push]

jobs:
  deploy_github_pages:
    runs-on: ubuntu-20.04
    name: Deploy GitHub Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test step
        id: test
        uses: ./
        with:
          main_branch: main
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Finish
        run: echo "Done"
