on:
  push:
    branches:
      - main

jobs:
  deploy_github_pages:
    runs-on: ubuntu-20.04
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        id: deploy
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
